export enum AssertType {
    ELEMENT_EXIST = "ELEMENT_EXIST",
    ELEMENT_NOT_EXIST = "ELEMENT_NOT_EXIST",
    TEXT_EXIST = "TEXT_EXIST",
    TEXT_NOT_EXIST = "TEXT_NOT_EXIST",
    ELEMENT_ARRTRIBUTE = "ELEMENT_ARRTRIBUTE",
    PAGE_ARRTRIBUTE = "PAGE_ARRTRIBUTE",
    CUSTOM="CUSTOM"

}


